version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./database:/app/database
    environment:
      - HUGGINGFACE_API_KEY=
      - GEMINI_API_KEY=
      - SERPAPI_KEY=
      - TWILIO_SID=your_twilio_sid
      - TWILIO_AUTH_TOKEN=your_twilio_auth_token
      - TWILIO_FROM_PHONE=your_twilio_phone
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped
